select id_korespondenta, 'dawne wojewodzkie' as typ_miejscowosci
                       from raporty.fsaps_v_adresy_do_mailingow
                       where miejscowosc in ( 'BIAŁA PODLASKA'	,
 'BIAŁYSTOK'	,
 'BIELSKO-BIAŁA'	,
 'BYDGOSZCZ'	,
 'CHEŁM'	,
 'CIECHANÓW'	,
 'CZĘSTOCHOWA'	,
 'ELBLĄG'	,
 'GDAŃSK'	,
 'GORZÓW WIELKOPOLSKI'	,
 'JELENIA GÓRA'	,
 'KALISZ'	,
 'KATOWICE'	,
 'KONIN'	,
 'KOSZALIN'	,
 'KRAKÓW'	,
 'KROSNO'	,
 'LEGNICA'	,
 'LESZNO'	,
 'LUBLIN'	,
 'ŁOMŻA'	,
 'ŁÓDŹ'	,
 'NOWY SĄCZ'	,
 'OLSZTYN'	,
 'OPOLE'	,
 'OSTROŁĘKA'	,
 'PIŁA'	,
 'PIOTRKÓW TRYBUNALSKI'	,
 'PŁOCK'	,
 'POZNAŃ'	,
 'PRZEMYŚL'	,
 'RADOM'	,
 'RZESZÓW'	,
 'SIEDLCE'	,
 'SIERADZ'	,
 'SKIERNIEWICE'	,
 'SŁUPSK'	,
 'SUWAŁKI'	,
 'SZCZECIN'	,
 'TARNOBRZEG'	,
 'TARNÓW'	,
 'TORUŃ'	,
 'WAŁBRZYCH'	,
 'WARSZAWA'	,
 'WŁOCŁAWEK'	,
 'ZAMOŚĆ'	,
 'ZIELONA GÓRA'	)